export const allBenefits: Record<string, {icon: string, label: string}> = {
  video_vip: { icon: 'vip-video.svg', label: 'VIP视频无限看' },
  manga_vip: { icon: 'vip-manga.svg', label: 'VIP漫画无限看' },
  novel_vip: { icon: 'comment.svg', label: 'VIP文字小说无限看' },
  audio_vip: { icon: 'audio-novel.svg', label: 'VIP有声小说无限听' },
  blogger_vip: { icon: 'Blogger.svg', label: 'VIP专属博主解锁' },
  dark_vip: { icon: 'vip-dark.svg', label: 'VIP暗网专区无限看' },
  anime_vip: { icon: 'vip-anime.svg', label: 'VIP动漫无限看' },
  video_coin: { icon: 'vip-video.svg', label: '金币视频无限看' },
  manga_coin: { icon: 'vip-manga.svg', label: '金币漫画无限看' },
  novel_coin: { icon: 'comment.svg', label: '金币文字小说无限看' },
  audio_coin: { icon: 'audio-novel.svg', label: '金币有声小说无限听' },
  blogger_coin: { icon: 'Blogger.svg', label: '原创博主解锁' },
  dark_coin: { icon: 'vip-dark.svg', label: '金币暗网专区无限看' },
  tiktok_coin: { icon: 'vip-tiktok.svg', label: '金币抖阴无限刷' },
  anime_coin: { icon: 'vip-anime.svg', label: '金币动漫无限看' },
  rocket: { icon: 'vip-rocket.svg', label: '高速线路' },
  service: { icon: 'service.svg', label: '客服一对一' },
  ad_free: { icon: 'ad-free.svg', label: '免广告' },
  tiktok_vip: { icon: 'vip-tiktok.svg', label: 'VIP抖阴无限刷' },
};
